// Projects/11-react/063-ecommerce/src/features/products/components/ProductCard.jsx
import { Link } from "react-router-dom";

function ProductCard({ product }) {
  return (
    <div className="border-2 border-gray-300 p-4 shadow rounded-xl">
      <div className="w-full aspect-square bg-gray-200 overflow-hidden">
        <img
          src={product.images[0]}
          alt={product.title}
          className="w-full h-full object-cover"
        />
      </div>
      <div className="border-t-2 border-gray-300 pt-4">
        <h2 className="font-semibold">{product.title}</h2>
        <p className="text-gray-600">{product.description}</p>
        <div className="flex items-center justify-between mt-4">
          <p className="text-xl font-bold">${product.price.toFixed(2)}</p>
          <Link to={`/products/${product.id}`} className="bg-blue-500 text-white p-2 rounded-lg hover:bg-blue-600 hover:cursor-pointer">
            View Details
          </Link>
        </div>
      </div>
    </div>
  )
}

export default ProductCard;

// ITI-Projects/16-Vue/074-VueShop/src/components/ProductCard.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
  product: Object
})

const discountedPrice = computed(() => {
  return props.product.discount ?
    props.product.price * (1 - props.product.discount / 100) :
    props.product.price;
});
</script>

<template>
  <div class="bg-base-200 w-75 shadow-md">
    <figure class="rounded-t-lg overflow-hidden h-50">
      <img :src="product.image" :alt="product.name" class="w-full" />
    </figure>
    <div class="p-4">
      <p>{{ product.name }}</p>
      <div class="flex items-baseline gap-2">
        <span class="text-primary">${{ discountedPrice.toFixed(2) }}</span>
        <span v-if="product.discount > 0" class="text-sm line-through text-gray-400">
          ${{ product.price }}
        </span>
        <span v-if="product.badge" class="badge badge-accent">{{ product.badge }}</span>
      </div>
    </div>
  </div>
</template>
